"""init

Revision ID: 104c9cb22f97
Revises:
Create Date: 2025-12-18 12:22:40.549914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "104c9cb22f97"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_finished", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recorder_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("sn", sa.String(length=50), nullable=False),
        sa.Column("sensitivity", sa.Float(), nullable=True),
        sa.Column("high_gain", sa.Float(), nullable=True),
        sa.Column("low_gain", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("owner", sa.String(length=100), nullable=True),
        sa.Column("recorder_channels", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand", "model", "sn", name="uix_recorder_brand_model_sn"),
        sa.UniqueConstraint("sn"),
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "deployment_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("recorder_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deploy_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gps_lat_plan", sa.Float(), nullable=True),
        sa.Column("gps_lon_plan", sa.Float(), nullable=True),
        sa.Column(
            "geom_plan",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            sa.Computed(
                "ST_SetSRID(ST_MakePoint(gps_lon_plan, gps_lat_plan), 4326)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("gps_lat_exe", sa.Float(), nullable=True),
        sa.Column("gps_lon_exe", sa.Float(), nullable=True),
        sa.Column(
            "geom_exe",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            sa.Computed(
                "ST_SetSRID(ST_MakePoint(gps_lon_exe, gps_lat_exe), 4326)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("depth", sa.Float(), nullable=True),
        sa.Column("fs", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_info.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorder_id"],
            ["recorder_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "name", "phase", name="uix_project_point_phase"
        ),
    )
    # GeoAlchemy2 會自動建置index所以這裡註解掉
    # op.create_index('idx_deployment_info_geom_exe', 'deployment_info', ['geom_exe'], unique=False, postgresql_using='gist')
    # op.create_index('idx_deployment_info_geom_plan', 'deployment_info', ['geom_plan'], unique=False, postgresql_using='gist')
    op.create_table(
        "audio_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("file_format", sa.String(length=10), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("record_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_duration", sa.Float(), nullable=True),
        sa.Column("fs", sa.Integer(), nullable=True),
        sa.Column("recorder_channel", sa.Integer(), nullable=True),
        sa.Column("audio_channels", sa.Integer(), nullable=True),
        sa.Column("target", sa.String(length=100), nullable=True),
        sa.Column("target_type", sa.Integer(), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=True),
        sa.Column("is_cold_storage", sa.Boolean(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployment_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(
        op.f("ix_audio_info_record_time"), "audio_info", ["record_time"], unique=False
    )
    op.create_table(
        "cetacean_info",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("audio_id", sa.Integer(), nullable=False),
        sa.Column("audio_channel", sa.Integer(), nullable=True),
        sa.Column("start_second", sa.Float(), nullable=True),
        sa.Column("end_second", sa.Float(), nullable=True),
        sa.Column("event_duration", sa.Float(), nullable=True),
        sa.Column("cetacean_call_type", sa.SmallInteger(), nullable=True),
        sa.Column("detection_method", sa.String(length=50), nullable=True),
        sa.Column("model_name", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audio_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cetacean_info_cetacean_call_type"),
        "cetacean_info",
        ["cetacean_call_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cetacean_info_cetacean_call_type"), table_name="cetacean_info"
    )
    op.drop_table("cetacean_info")
    op.drop_index(op.f("ix_audio_info_record_time"), table_name="audio_info")
    op.drop_table("audio_info")
    op.drop_index(
        "idx_deployment_info_geom_plan",
        table_name="deployment_info",
        postgresql_using="gist",
    )
    op.drop_index(
        "idx_deployment_info_geom_exe",
        table_name="deployment_info",
        postgresql_using="gist",
    )
    op.drop_table("deployment_info")
    op.drop_table("user_info")
    op.drop_table("recorder_info")
    op.drop_table("project_info")
    # ### end Alembic commands ###
