"""add bits to recorder_info, recorder_sn is_for_report header_warning to audio_info

Revision ID: 8d117cb597a8
Revises: 89e57293b088
Create Date: 2026-02-25 02:12:43.643803

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "8d117cb597a8"
down_revision: Union[str, Sequence[str], None] = "89e57293b088"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_info", sa.Column("recorder_sn", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "audio_info",
        sa.Column(
            "is_for_report",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "audio_info", sa.Column("header_warning", sa.String(length=500), nullable=True)
    )
    op.create_index(
        op.f("ix_audio_info_recorder_sn"), "audio_info", ["recorder_sn"], unique=False
    )
    op.add_column("recorder_info", sa.Column("bits", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recorder_info", "bits")
    op.drop_index(op.f("ix_audio_info_recorder_sn"), table_name="audio_info")
    op.drop_column("audio_info", "header_warning")
    op.drop_column("audio_info", "is_for_report")
    op.drop_column("audio_info", "recorder_sn")
    # ### end Alembic commands ###
