"""empty message

Revision ID: a6437fee202d
Revises: fix_deployment_idx
Create Date: 2026-02-10 05:07:27.678084

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6437fee202d'
down_revision: str | Sequence[str] | None = 'fix_deployment_idx'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_info', sa.Column('project_type', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('uq_project_name_zh'), 'project_info', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_project_name_zh'), 'project_info', ['name_zh'], postgresql_nulls_not_distinct=False)
    op.drop_column('project_info', 'project_type')
    # ### end Alembic commands ###
