"""update model structure

Revision ID: 530173a93222
Revises: 104c9cb22f97
Create Date: 2026-01-09 16:05:44.497425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "530173a93222"
down_revision: Union[str, Sequence[str], None] = "104c9cb22f97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "point_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gps_lat_plan", sa.Float(), nullable=True),
        sa.Column("gps_lon_plan", sa.Float(), nullable=True),
        sa.Column(
            "geom_plan",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            sa.Computed(
                "ST_SetSRID(ST_MakePoint(gps_lon_plan, gps_lat_plan), 4326)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("depth_plan", sa.Float(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uix_project_point"),
    )
    op.add_column("audio_info", sa.Column("is_for_report", sa.Boolean(), nullable=True))
    op.add_column(
        "audio_info",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "cetacean_info", sa.Column("cetacean_species", sa.SmallInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_cetacean_info_cetacean_species"),
        "cetacean_info",
        ["cetacean_species"],
        unique=False,
    )
    op.add_column(
        "deployment_info", sa.Column("point_id", sa.Integer(), nullable=False)
    )
    op.add_column("deployment_info", sa.Column("depth_exe", sa.Float(), nullable=True))
    op.add_column(
        "deployment_info", sa.Column("sensitivity", sa.Float(), nullable=True)
    )
    op.add_column("deployment_info", sa.Column("gain", sa.Float(), nullable=True))
    op.add_column(
        "deployment_info", sa.Column("description", sa.String(), nullable=True)
    )
    op.drop_index(
        op.f("idx_deployment_info_geom_plan"),
        table_name="deployment_info",
        postgresql_using="gist",
    )
    op.drop_constraint(
        op.f("uix_project_point_phase"), "deployment_info", type_="unique"
    )
    op.create_unique_constraint(
        "uix_point_start_time", "deployment_info", ["point_id", "start_time"]
    )
    op.drop_constraint(
        op.f("deployment_info_project_id_fkey"), "deployment_info", type_="foreignkey"
    )
    op.create_foreign_key(None, "deployment_info", "point_info", ["point_id"], ["id"])
    op.drop_column("deployment_info", "geom_plan")
    op.drop_column("deployment_info", "name")
    op.drop_column("deployment_info", "gps_lon_plan")
    op.drop_column("deployment_info", "project_id")
    op.drop_column("deployment_info", "phase")
    op.drop_column("deployment_info", "gps_lat_plan")
    op.drop_column("deployment_info", "depth")
    op.add_column(
        "project_info", sa.Column("owner", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "project_info", sa.Column("contractor", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "project_info", sa.Column("contact_name", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "project_info", sa.Column("contact_phone", sa.String(length=50), nullable=True)
    )
    op.add_column("recorder_info", sa.Column("description", sa.String(), nullable=True))
    op.alter_column(
        "recorder_info",
        "sensitivity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recorder_info",
        "sensitivity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("recorder_info", "description")
    op.drop_column("project_info", "contact_phone")
    op.drop_column("project_info", "contact_name")
    op.drop_column("project_info", "contractor")
    op.drop_column("project_info", "owner")
    op.add_column(
        "deployment_info",
        sa.Column(
            "depth",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deployment_info",
        sa.Column(
            "gps_lat_plan",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deployment_info",
        sa.Column("phase", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "deployment_info",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "deployment_info",
        sa.Column(
            "gps_lon_plan",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "deployment_info",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "deployment_info",
        sa.Column(
            "geom_plan",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            sa.Computed(
                "st_setsrid(st_makepoint(gps_lon_plan, gps_lat_plan), 4326)",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "deployment_info", type_="foreignkey")
    op.create_foreign_key(
        op.f("deployment_info_project_id_fkey"),
        "deployment_info",
        "project_info",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint("uix_point_start_time", "deployment_info", type_="unique")
    op.create_unique_constraint(
        op.f("uix_project_point_phase"),
        "deployment_info",
        ["project_id", "name", "phase"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_deployment_info_geom_plan"),
        "deployment_info",
        ["geom_plan"],
        unique=False,
        postgresql_using="gist",
    )
    op.drop_column("deployment_info", "description")
    op.drop_column("deployment_info", "gain")
    op.drop_column("deployment_info", "sensitivity")
    op.drop_column("deployment_info", "depth_exe")
    op.drop_column("deployment_info", "point_id")
    op.drop_index(op.f("ix_cetacean_info_cetacean_species"), table_name="cetacean_info")
    op.drop_column("cetacean_info", "cetacean_species")
    op.drop_column("audio_info", "created_at")
    op.drop_column("audio_info", "is_for_report")
    op.drop_index(
        "idx_point_info_geom_plan", table_name="point_info", postgresql_using="gist"
    )
    op.drop_table("point_info")
    # ### end Alembic commands ###
