"""add indexes to foreign keys

Revision ID: 7ce5aa0ca14d
Revises: c29e7991686d
Create Date: 2026-01-28 16:16:19.463577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  


# revision identifiers, used by Alembic.
revision: str = '7ce5aa0ca14d'
down_revision: Union[str, Sequence[str], None] = 'c29e7991686d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audio_info_deployment_id'), 'audio_info', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_info_point_id'), 'deployment_info', ['point_id'], unique=False)
    op.create_index(op.f('ix_deployment_info_recorder_id'), 'deployment_info', ['recorder_id'], unique=False)
    op.create_index(op.f('ix_point_info_project_id'), 'point_info', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_info_project_id'), table_name='point_info')
    op.drop_index(op.f('ix_deployment_info_recorder_id'), table_name='deployment_info')
    op.drop_index(op.f('ix_deployment_info_point_id'), table_name='deployment_info')
    op.drop_index(op.f('ix_audio_info_deployment_id'), table_name='audio_info')
    # ### end Alembic commands ###
