"""add project contact fields

Revision ID: add_project_contact_fields
Revises: 104c9cb22f97
Create Date: 2026-01-20 17:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "add_project_contact_fields"
down_revision: Union[str, None] = "c2b79eb98a1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_info", sa.Column("contact_email", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_info", "contact_email")
    # ### end Alembic commands ###
