"""implement soft delete schema

Revision ID: c29e7991686d
Revises: c7ec2b124eb8
Create Date: 2026-01-26 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c29e7991686d"
down_revision: Union[str, Sequence[str], None] = "c7ec2b124eb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Audio Info
    op.add_column(
        "audio_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "audio_info", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("audio_info", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.drop_constraint("audio_info_object_key_key", "audio_info", type_="unique")
    op.create_index(
        "ix_audio_object_key_active",
        "audio_info",
        ["object_key"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # Deployment Info
    op.add_column(
        "deployment_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "deployment_info",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "deployment_info", sa.Column("deleted_by", sa.Integer(), nullable=True)
    )
    op.drop_constraint("uq_deployment_point_phase", "deployment_info", type_="unique")
    op.drop_constraint(
        "uq_deployment_point_start_time", "deployment_info", type_="unique"
    )
    op.create_index(
        "uq_deployment_point_phase_active",
        "deployment_info",
        ["point_id", "phase"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "uq_deployment_point_start_time_active",
        "deployment_info",
        ["point_id", "start_time"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # Point Info
    op.add_column(
        "point_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "point_info", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("point_info", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.drop_constraint("uq_point_project_name", "point_info", type_="unique")
    op.create_index(
        "uq_point_project_name_active",
        "point_info",
        ["project_id", "name"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # Project Info
    op.add_column(
        "project_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "project_info",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("project_info", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.drop_constraint("project_info_name_key", "project_info", type_="unique")
    op.create_index(
        "ix_project_name_active",
        "project_info",
        ["name"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_project_name_zh_active",
        "project_info",
        ["name_zh"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # Recorder Info
    op.add_column(
        "recorder_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "recorder_info",
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("recorder_info", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.drop_constraint("uq_recorder_brand_model_sn", "recorder_info", type_="unique")
    op.create_index(
        "uq_recorder_brand_model_sn_active",
        "recorder_info",
        ["brand", "model", "sn"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # User Info
    op.add_column(
        "user_info",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "user_info", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("user_info", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.drop_constraint("user_info_email_key", "user_info", type_="unique")
    op.create_index(
        "ix_user_email_active",
        "user_info",
        ["email"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # User Info
    op.drop_index(
        "ix_user_email_active",
        table_name="user_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint("user_info_email_key", "user_info", ["email"])
    op.drop_column("user_info", "deleted_by")
    op.drop_column("user_info", "deleted_at")
    op.drop_column("user_info", "is_deleted")

    # Recorder Info
    op.drop_index(
        "uq_recorder_brand_model_sn_active",
        table_name="recorder_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint(
        "uq_recorder_brand_model_sn", "recorder_info", ["brand", "model", "sn"]
    )
    op.drop_column("recorder_info", "deleted_by")
    op.drop_column("recorder_info", "deleted_at")
    op.drop_column("recorder_info", "is_deleted")

    # Project Info
    op.drop_index(
        "ix_project_name_zh_active",
        table_name="project_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "ix_project_name_active",
        table_name="project_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint("project_info_name_key", "project_info", ["name"])
    op.drop_column("project_info", "deleted_by")
    op.drop_column("project_info", "deleted_at")
    op.drop_column("project_info", "is_deleted")

    # Point Info
    op.drop_index(
        "uq_point_project_name_active",
        table_name="point_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint(
        "uq_point_project_name", "point_info", ["project_id", "name"]
    )
    op.drop_column("point_info", "deleted_by")
    op.drop_column("point_info", "deleted_at")
    op.drop_column("point_info", "is_deleted")

    # Deployment Info
    op.drop_index(
        "uq_deployment_point_start_time_active",
        table_name="deployment_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.drop_index(
        "uq_deployment_point_phase_active",
        table_name="deployment_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint(
        "uq_deployment_point_start_time", "deployment_info", ["point_id", "start_time"]
    )
    op.create_unique_constraint(
        "uq_deployment_point_phase", "deployment_info", ["point_id", "phase"]
    )
    op.drop_column("deployment_info", "deleted_by")
    op.drop_column("deployment_info", "deleted_at")
    op.drop_column("deployment_info", "is_deleted")

    # Audio Info
    op.drop_index(
        "ix_audio_object_key_active",
        table_name="audio_info",
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_unique_constraint(
        "audio_info_object_key_key", "audio_info", ["object_key"]
    )
    op.drop_column("audio_info", "deleted_by")
    op.drop_column("audio_info", "deleted_at")
    op.drop_column("audio_info", "is_deleted")
    # ### end Alembic commands ###
