"""add name_zh to project

Revision ID: c7ec2b124eb8
Revises: add_project_contact_fields
Create Date: 2026-01-26 11:28:35.928831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ec2b124eb8'
down_revision: Union[str, Sequence[str], None] = 'add_project_contact_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cetacean_info_cetacean_call_type'), table_name='cetacean_info')
    op.drop_index(op.f('ix_cetacean_info_cetacean_species'), table_name='cetacean_info')
    op.drop_table('cetacean_info')
    op.alter_column('audio_info', 'object_key',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=False)
    op.drop_column('audio_info', 'is_for_report')
    op.drop_column('audio_info', 'created_at')
    op.alter_column('deployment_info', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('deployment_info', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('uix_point_phase'), 'deployment_info', type_='unique')
    op.drop_constraint(op.f('uix_point_start_time'), 'deployment_info', type_='unique')
    op.create_index(op.f('ix_deployment_info_id'), 'deployment_info', ['id'], unique=False)
    op.create_unique_constraint('uq_deployment_point_phase', 'deployment_info', ['point_id', 'phase'])
    op.create_unique_constraint('uq_deployment_point_start_time', 'deployment_info', ['point_id', 'start_time'])
    op.alter_column('point_info', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('uix_project_point'), 'point_info', type_='unique')
    op.create_index(op.f('ix_point_info_id'), 'point_info', ['id'], unique=False)
    op.create_unique_constraint('uq_point_project_name', 'point_info', ['project_id', 'name'])
    op.drop_column('point_info', 'end_time')
    op.drop_column('point_info', 'start_time')
    op.add_column('project_info', sa.Column('name_zh', sa.String(length=100), nullable=True))
    op.alter_column('project_info', 'owner',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project_info', 'contractor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project_info', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project_info', 'contact_phone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('project_info', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_project_info_id'), 'project_info', ['id'], unique=False)
    op.alter_column('recorder_info', 'brand',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('recorder_info', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('recorder_info', 'sn',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('recorder_info', 'status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('recorder_info', 'recorder_channels',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('recorder_info', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('recorder_info_sn_key'), 'recorder_info', type_='unique')
    op.drop_constraint(op.f('uix_recorder_brand_model_sn'), 'recorder_info', type_='unique')
    op.create_index(op.f('ix_recorder_info_id'), 'recorder_info', ['id'], unique=False)
    op.create_unique_constraint('uq_recorder_brand_model_sn', 'recorder_info', ['brand', 'model', 'sn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recorder_brand_model_sn', 'recorder_info', type_='unique')
    op.drop_index(op.f('ix_recorder_info_id'), table_name='recorder_info')
    op.create_unique_constraint(op.f('uix_recorder_brand_model_sn'), 'recorder_info', ['brand', 'model', 'sn'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('recorder_info_sn_key'), 'recorder_info', ['sn'], postgresql_nulls_not_distinct=False)
    op.alter_column('recorder_info', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('recorder_info', 'recorder_channels',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recorder_info', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('recorder_info', 'sn',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('recorder_info', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('recorder_info', 'brand',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_project_info_id'), table_name='project_info')
    op.alter_column('project_info', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('project_info', 'contact_phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('project_info', 'contact_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('project_info', 'contractor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('project_info', 'owner',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('project_info', 'name_zh')
    op.add_column('point_info', sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('point_info', sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_point_project_name', 'point_info', type_='unique')
    op.drop_index(op.f('ix_point_info_id'), table_name='point_info')
    op.create_unique_constraint(op.f('uix_project_point'), 'point_info', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('point_info', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint('uq_deployment_point_start_time', 'deployment_info', type_='unique')
    op.drop_constraint('uq_deployment_point_phase', 'deployment_info', type_='unique')
    op.drop_index(op.f('ix_deployment_info_id'), table_name='deployment_info')
    op.create_unique_constraint(op.f('uix_point_start_time'), 'deployment_info', ['point_id', 'start_time'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uix_point_phase'), 'deployment_info', ['point_id', 'phase'], postgresql_nulls_not_distinct=False)
    op.alter_column('deployment_info', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('deployment_info', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.add_column('audio_info', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('audio_info', sa.Column('is_for_report', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('audio_info', 'object_key',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.create_table('cetacean_info',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('audio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audio_channel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('end_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('event_duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cetacean_call_type', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('detection_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('cetacean_species', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_info.id'], name=op.f('cetacean_info_audio_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cetacean_info_pkey'))
    )
    op.create_index(op.f('ix_cetacean_info_cetacean_species'), 'cetacean_info', ['cetacean_species'], unique=False)
    op.create_index(op.f('ix_cetacean_info_cetacean_call_type'), 'cetacean_info', ['cetacean_call_type'], unique=False)
    # ### end Alembic commands ###
