"""add unique constraint to project name_zh

Revision ID: db16e45b373d
Revises: c7ec2b124eb8
Create Date: 2026-01-26 15:50:01.485289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  


# revision identifiers, used by Alembic.
revision: str = 'db16e45b373d'
down_revision: Union[str, Sequence[str], None] = 'c7ec2b124eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_name_zh', 'project_info', ['name_zh'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_name_zh', 'project_info', type_='unique')
    # ### end Alembic commands ###
